#!/bin/sh

SBBS_DIR=$(dirname $0)
VERSION="$(cat ${SBBS_DIR}/project.clj | head -1 | awk '{print $3;}' | sed -e 's/"//g')"
JARFILE="sbbs-${VERSION}-standalone.jar"

if [ -z "${SBBS_CATEGORYDB}" ]; then
    export SBBS_CATEGORYDB="sbbs_categories"
fi

if [ -z "${SBBS_COMMENTDB}" ]; then
    export SBBS_COMMENTDB="sbbs_comments"
fi

if [ -z "${SBBS_USERDB}" ]; then
    export SBBS_USERDB="sbbs_users"
fi

echo "loading sbbs..."
echo
echo
java -jar "${SBBS_DIR}/$JARFILE"
